Microchip addition of new devices PIC32CX_SG41, PIC32CX_SG60, PIC32CX_SG61
zephyrproject-rtos/hal_microchip pull request #21
Opened 2024-07-09 17:20 UTC by MyGh64605

These devices are compatible with ATSAMD/E XX series of devices that are currently incorporated within Zephyr.

These modifications are for the HAL layer only.
Boards will be added later.

2024-07-09 17:51 UTC, MyGh64605 commented
Question, should I create a pull request for the main Zephyr project or wait until this request is approved.

2024-07-09 17:54 UTC, MyGh64605 commented
@nandojve This is first pull request to incorporate the PIC32CX SG devices, that are compatible with the ATDAMD/E XX devices.

2024-07-09 19:07 UTC, kartben commented
> Question, should I create a pull request for the main Zephyr project or wait until this request is approved.
> 

https://docs.zephyrproject.org/latest/develop/modules.html#process-for-submitting-changes-to-existing-modules

2024-07-09 19:12 UTC, scottwcpg requested changes
Please move into subfolder.  DTS can be at the top level because it has subfolders for vendor/chip_family.

2024-07-09 19:12 UTC, scottwcpg commented on CMakeLists.txt
add_subdirectory(mplabx) add this path to MEC_HAL (CPG old stuff), MPFS_HAL (microsemi RISC-V), and MEC5_HAL (CPU new stuff).  Should be add_subdirectory_ifdef

2024-07-09 19:12 UTC, scottwcpg commented on README.md
All the original content is gone.  Many of your instructions do not apply to the the other HAL's.  These HAL's use the zephyr SDK toolchain.

2024-07-09 19:12 UTC, scottwcpg commented on README.md
> +## The standard API
This applies to our HAL only.  The others use their own naming convention.

2024-07-09 19:12 UTC, scottwcpg commented on include/dt-bindings/pinctrl/microchip_pic32cxsg_pinctrl.h
> +/*
This folder is at the top level.  Most hal_vendor folders have subdirectories containing the whole chip family. mec, mec5, mpfs contain all the specific stuff for those chip families.  Is it possible for you to put your stuff in a subdirectory also, so we are all consistent and isolated?

2024-07-10 16:39 UTC, nandojve commented
> @nandojve This is first pull request to incorporate the PIC32CX SG devices, that are compatible with the ATDAMD/E XX devices.

Ok, I'll start to review soon.

2024-07-15 19:15 UTC, nandojve requested changes
Hi @MyGh64605 ,

> Question, should I create a pull request for the main Zephyr project or wait until this request is approved.

It is very important to follow the [how-to-submit-code](https://github.com/zephyrproject-rtos/hal_atmel/blob/master/README.md#how-to-submit-code). I also recommend this old side that help to understand how I usually expect a commit message https://cbea.ms/git-commit. Not a must - **desirable**.

It is important organize the commit brief message to allow easy filtering. Usually I start this way:

1- More than one device, try group by family
2- functionality: family or device. Try get some inspiration from `hal_atmel`:
```shell
* c1c4410 - docs: Improve documentation (1 year, 4 months ago) <Gerson Fernando Budke>
* d45adfb - samc20: samc21: Add ADC_INPUTCTRL internal ground for ADC Driver (1 year, 9 months ago) <Kamil Serwus>
* ffe9191 - pinctrl: sam-c2x: Add pinconfigs and include files (1 year, 9 months ago) <Kamil Serwus>
* 3eaaa0b - ext: Import Atmel SAMC20 header files from ASF library (1 year, 9 months ago) <Kamil Serwus>
* a269f63 - ext: Import Atmel SAMC21 header files from ASF library (1 year, 9 months ago) <Kamil Serwus>
* 840b6ac - sam0: Add revisions to soc includes (1 year, 9 months ago) <Kamil Serwus>
* 43c73d8 - sam4l: Add US_MR_CHRL_{n}_BIT Register Aliases for USART Driver (1 year, 9 months ago) <Nick Kraus>
* 1d237f2 - samv71b: Fix CIDR for V71 Revision B Silicon (1 year, 11 months ago) <Nick Kraus>
* bb4e710 - CMakeLists.txt: Add include directory only for atmel devices (2 years ago) <Yonatan Schachter>
* a486271 - winc1500: nmspi: Fix compiler warning (2 years, 1 month ago) <Kumar Gala>
* 7458978 - ext: winc1500: Rename function to avoid name clash (2 years, 1 month ago) <Ole Morten Haaland>
* 7518d0b - pinctrl: sam-r34-r35: Add pinconfigs and include files (2 years, 3 months ago) <Attie Grande>
* 8989ec4 - pinctrl: sam-l21: Add pinconfigs and include files (2 years, 3 months ago) <Attie Grande>
* 7e9d3fc - ext: Import Atmel SAMR35 header files from ASF library (2 years, 3 months ago) <Attie Grande>
* 4749709 - ext: Import Atmel SAMR34 header files from ASF library (2 years, 3 months ago) <Attie Grande>
* ceacbcb - ext: Import Atmel SAML21 header files from ASF library (2 years, 3 months ago) <Attie Grande>
* 2c2ce9f - ci: license_check: Update to scancode action v4 (2 years, 4 months ago) <Stephanos Ioannidis>
* 78c5567 - samv71: patch: Fix XDMAC_CHID register name (2 years, 4 months ago) <Gerson Fernando Budke>
* 94d8d86 - pinctrl: pinconfigs: Add README file (2 years, 4 months ago) <Gerson Fernando Budke>
* 5efcf60 - pinctrl: sam-d51-d53-d54: Add pinconfigs and include files (2 years, 4 months ago) <Gerson Fernando Budke>
* 5a4f715 - pinctrl: sam-r21: Add pinconfigs and include files (2 years, 4 months ago) <Gerson Fernando Budke>
* 3d10116 - pinctrl: sam-d20-d21-da1: Add pinconfigs and include files (2 years, 4 months ago) <Gerson Fernando Budke>
* 1876356 - pinctrl: sam-s70-e70-v7x: Add pinconfigs and include files (2 years, 4 months ago) <Gerson Fernando Budke>
* b33b97a - pinctrl: sam-4s-4sa-4sd: Add pinconfigs and include files (2 years, 4 months ago) <Gerson Fernando Budke>
* 845b8f2 - pinctrl: sam-4l: Add pinconfigs and include files (2 years, 4 months ago) <Gerson Fernando Budke>
* 674b12d - pinctrl: sam-4e: Add pinconfigs and include files (2 years, 4 months ago) <Gerson Fernando Budke>
* ac2bac9 - pinctrl: sam-3x: Add pinconfigs and include files (2 years, 4 months ago) <Gerson Fernando Budke>
* 527de70 - pinctrl: Add pinctrl tests (2 years, 4 months ago) <Gerson Fernando Budke>
* 9597144 - pinctrl: Add pinctrl script (2 years, 4 months ago) <Gerson Fernando Budke>
* 45cb8f8 - patch: samd21/r21: Normalize underscore defines (2 years, 4 months ago) <Gerson Fernando Budke>
* 7c24242 - patch: samd21: Correct missing underscore in defines for variants (2 years, 5 months ago) <rocky134>
```

It is mandatory when add a new platform to have a new board at same time. The board only needs a serial port on pooling mode that runs the hello world application. This means that we need to align hal / soc / devicetree / board. On the remaining features will be add incrementally. This allows us to do a good review process and make sure that both tests are Ok and code is on a usable stage.

2024-07-15 19:15 UTC, nandojve commented on CMakeLists.txt
I think this is a good opportunity to start organize the content. I believe that having names like ASF or MPLABX do not help. The content that are placed inside those folders are platform specific, The platform directory should have a tree that follows an specific family. Inside each family the variants will be placed. The below tree presents 2 well know families `sam` and `sam0`. The new `pic32cxsg` should be organized in the same manner.  I let to you propose the names but I believe the content will be well organized as in the below tree.

Notes:

1- Add the `.github` rules that are available on `hal_atmel` to check if the licenses are compliance with Zephyr rules.
2- The mec/mec5/mpfs are candidates to be moved inside platform [Improvement - not part of this PR]

```
.
├── .github
│   ├── license_config.yml
│   └── workflows
│       ├── license_check.yml
│       └── test.yml
├── platform
│   ├── CMakeLists.txt
│   ├── common
│   │   ├── CMakeLists.txt
│   │   └── components
│   ├── ? family name
│   │   ├── CMakeLists.txt
│   │   └── include
│   │       ├── ? part variant name
│   │       └── next gen ?
│   ├── sam
│   │   ├── CMakeLists.txt
│   │   └── include
│   │       ├── sam3x
│   │       ├── sam4e
│   │       ├── sam4l
│   │       ├── sam4s
│   │       ├── same70
│   │       ├── same70b
│   │       ├── samv71
│   │       └── samv71b
│   └── sam0
│       ├── CMakeLists.txt
│       └── include
│           ├── CMakeLists.txt
│           ├── samc20
│           ├── samc20n
│           ├── samc21
│           ├── samc21n
│           ├── samd20
│           ├── samd21
│           ├── samd51
│           ├── same51
│           ├── same53
│           ├── same54
│           ├── saml21
│           ├── samr21
│           ├── samr34
│           └── samr35
├── CMakeLists.txt
├── include
│   └── dt-bindings
│       └── pinctrl
├── pinconfigs
│   ├── README.md
│   ├── sam-3x.yml
│   ├── sam-4e.yml
│   ├── sam-4l.yml
│   ├── sam-4s-4sa-4sd.yml
│   ├── sam-c2x.yml
│   ├── sam-d2x-da1-abcd.yml
│   ├── sam-d5x-e5x.yml
│   ├── sam-l21.yml
│   ├── sam-r21.yml
│   ├── sam-r34-r35.yml
│   └── sam-s70-e70-v7x.yml
├── README.md
├── scripts
│   ├── README.md
│   ├── requirements-dev.txt
│   ├── requirements-test.txt
│   ├── requirements.txt
│   ├── sampinctrl.py
│   └── tests
│       └── sampinctrl
└── zephyr

```

2024-07-15 19:15 UTC, nandojve commented on include/dt-bindings/pinctrl/microchip_pic32cxsg_pinctrl.h
> +#ifndef DT_BINDINGS_PINCTRL_MICROCHIP_PIC32CXSG_PINCTRL_H_
I'm glad to see that MCHP appreciate the work that was made on the hal_atmel. This means that all the files that have copyright that are base for some work in this repository and were captured from `hal_atmel` or even are inspirations for some derived work in this repository must have the original copyright.

2024-07-15 19:15 UTC, nandojve commented on mplabx/pic32cxsg/CMakeLists.txt
> +add_subdirectory(include)
File should have a newline at end.
Fix all the files that apply.

2024-07-15 19:15 UTC, nandojve commented on mplabx/pic32cxsg/include/pic32cxsg41/component-version.h
> +/*
run `find * type f -print0 | xargs -0 dos2unix -k` on all the files imported and make sure they are using `utf-8` format.

2024-07-18 19:32 UTC, MyGh64605 commented on mplabx/pic32cxsg/include/pic32cxsg41/component-version.h
> +/*
Good afternoon, will this command actually 'fixup' the files and provide a list of modified files ?

2024-07-18 19:59 UTC, MyGh64605 commented on mplabx/pic32cxsg/CMakeLists.txt
> +add_subdirectory(include)
Good afternoon, 
I will make the suggested modifications.

Will multiple pull requests need to be made ?
This one for hal_microchip and
One to add the board files ?
One to modify 'west.yml' ?
One to add the soc files etc ...... ?

FYI, 
I have created or modified all the pertinent files within the main Zephyr directory. Created a 'Hello World' project for both of the evaluation boards to be added.
The 'Hello World' project compiles without error.

2024-07-18 20:10 UTC, MyGh64605 commented on mplabx/pic32cxsg/include/pic32cxsg41/component-version.h
> +/*
Good afternoon,

error after running this command

"'xargs' is not recognized as an internal or external command,
operable program or batch file."

2024-07-19 08:54 UTC, con-pax commented on CMakeLists.txt
I think @nandojve suggestion for organization is a good one. have you thought about it @scottwcpg?

2024-07-19 09:48 UTC, nandojve commented on CMakeLists.txt
I think this can make more sense when you think about integration of hal_mchp/atmel in the future. So, everything goes in the right place and future generations will be side by side. This makes zephyr soc configuration far more easy to handle since hal will be same for MCUs independent of the core ARM/RISC-V etc.

2024-07-30 18:51 UTC, MyGh64605 commented
Have updated the hal_microchip PIC32CX SG files.

Associated pull request for the addition of the PIC32CX_SG devices to zephyr main:
https://github.com/zephyrproject-rtos/zephyr/pull/76503

2024-08-01 12:14 UTC, nandojve requested changes
Overall LGTM. I'll suggest to change the title to `pic32c: Introduce hal platform`

2024-08-01 12:14 UTC, nandojve commented on scripts/pic32cxsgpinctrl.py
> +# Copyright (c) 2024 Microchip
You should keep original copyright with the new one, even when you rename a file.

2024-08-01 12:14 UTC, nandojve commented on scripts/pic32pinctrl.py
> +# Copyright (c) 2024 Microchip
You should keep original copyright with the new one, even when you rename a file.

2024-08-01 12:14 UTC, nandojve commented on README.md
I still think to have a `platform` folder name instead `pic32c` seems better for the long run. Then, when moving `sam`, `sam0` they will be side by side with `pic32cxsg` instead creating 2 new folders on the root folder.

2024-08-08 11:20 UTC, nandojve commented
Please, do not execute merge branch. Always rebase your commits (Fast Forward Only) on top of the main. The goal is to have a clean history

2024-12-02 22:29 UTC, MyGh64605 commented
Closing PR#21. superseded by PR#24.

2024-12-02 22:29 UTC, closed without merging